name: concentric
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - scipy
  - sympy
  - matplotlib
  - plotly
  - jupyter
  - jupyterlab
  - pandas
  - seaborn
  - scikit-learn
  - ipywidgets
  - pip
  - pip:
    - nbformat
